inherit: ["config.yml"]
stylesheet: vivliostyle-a6.css
# cover: null
coverimage: cover.png
titlepage: title.png
# titlefile: title.xhtml
colophon: true
backcover: backcover.xhtml
# catalogfile: catalog.yml
bookname: book
booktitle: "並行現実小説集　第３巻"
subtitle: "２０２３年秋〜２０２４年年始"
highlight:
  html: "rouge"