inherit: ["config.yml"]
# catalogfile: catalog-download.yml
bookname: book-epub
cover: null
coverimage: cover.xhtml
titlepage: true
titlefile: title.xhtml
colophon: colophon.xhtml
backcover: backcover.xhtml