inherit: ["config.yml"]
stylesheet: vivliostyle-a6.css
cover: false
coverimage: null
titlepage: true
titlefile: title.xhtml
colophon: colophon.xhtml
backcover: null
# catalogfile: catalog.yml
bookname: book
booktitle: "並行現実小説集　第３巻"
subtitle: "２０２３年秋〜２０２４年年始"
highlight:
  html: "rouge"