inherit: ["config.yml"]
stylesheet: vivliostyle-a6.css
titlefile: images/title.png
cover: null
coverimage: null
colophon: images/colophon.png
# catalogfile: catalog.yml
bookname: book
highlight:
  html: "rouge"