inherit: ["config.yml"]
bookname: book-print-pdf
# prt: ねこのしっぽ
coverimage: null
texdocumentclass: ["review-jlreq", "media=print,paper=a6,fontsize=8pt,serial_pagination=true,hiddenfolio=shippo,startpage=3,tate,twoside,onecolumn,openany"]