inherit: ["config.yml"]
stylesheet: vivliostyle-a6.css
titlefile: title.xhtml
cover: null
coverimage: null
colophon: colophon.xhtml
# catalogfile: catalog.yml
bookname: book
highlight:
  html: "rouge"